name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allow manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: athul/waka-readme@v2.2.0
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Updated WakaTime stats"
          git push

