name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 */3 * * *' # Runs every 3 hours
  workflow_dispatch: # Allow manual triggering
  push: {branches: ["master", "main"]}
jobs:
  update-readme:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@latest
        with:
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors-graphs, os-graphs
          plugin_wakatime_languages_ignored: markdown, plaintext, text, xml, yaml, JSON
          plugin_wakatime_days: 365
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

