name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allow manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: WakaTime Readme Stats
        uses: denvercoder1/github-readme-wakatime@v1.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Updated WakaTime stats"
          git push

